# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Sunggweon Hyeong
baseurl:        ""
url:            "https://iosdevted.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Sunggweon Hyeong
  url:          "https://iosdevted.github.io"
  email:        devted@protonmail.com 
  github:       cielgrisdemoscou
  #twitter:

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/iosdevted/iosdevted.github.io
